### ISSUE TITLE
[Version: ] Error when clicking  button "Create" for uploading attachments in Work Zone standard environment(managed approuter).

### ISSUE THREAD

**Issue by micol92** [cap-js/attachments#110]
**Describe the bug**

I'm developing the CAP fullstack application using Build Code. For your reference, I'm following the link "https://www.youtube.com/watch?v=4o2Swj89zxU"
I've completed application using Build Code and then deployed it into Work Zone HTML5 repository. Deployment was performed successfully
However, I've met an error(Internal Server Error) like image below when clicking button "Create"  for uploading attachments in Work Zone standard environment.

![image](https://github.com/user-attachments/assets/bcce01e9-674c-4260-9ed2-bc9aaef0d186)

Applicaiton error log is attached, please check it.
[ErrorLog.pptx](https://github.com/user-attachments/files/17662576/ErrorLog.pptx)
 

**To Reproduce**
I've uploaded development source from Build Code into github link(https://github.com/micol92/BC-troubleshooting)

**Expected behavior**
I've confirmed that attachement feature works well when I've deployed it using standalone approuter.
As Work Zone includes managed approuter, it looks managed approuter causes error.
The managed approuter and standalone approuter are showing different results.

[ ] is it a regression issue? 

**Screenshots**

**Customer Info**
Company: xyz.

**Comment by Dipto-at-sap** [comment]
Hi @micol92,

I went through your application's codebase, and while running the application in the local environment, I found that we're getting that internal server error even if we don't attach any attachments. I think it's because of one of your custom handlers, So it's not a bug related to attachments.

Thank you.

<img width="1728" alt="Screenshot 2024-12-08 at 8 51 43 PM" src="https://github.com/user-attachments/assets/3e4e3703-dc12-442b-b628-935af785c54e">
